services:
  app:
    env_file: 
      - path: ./.env 
        required: true
    image: "aviumlabs/phoenix:latest-alpine" 
    volumes:
      - ./src:${WORKINGDIR}/$APP_NAME
    ports:
      - "4000:4000"
    working_dir: ${WORKINGDIR}/$APP_NAME
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - postgres_password
  db:
    env_file: 
      - path: ./.env 
        required: true
    image: "postgres:17-alpine3.21"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_password

volumes:
  db_data:

secrets:
  postgres_password:
    file: ./.secret_db
