services:
  app:
    env_file: 
      - path: ./.env 
        required: true
    image: "aviumlabs/phoenix:latest-alpine" 
    volumes:
      - ./src:${APP_CONTAINER_ROOT}
    ports:
      - "4000:4000"
    working_dir: ${WORKINGDIR}
    depends_on:
      db:
        condition: service_healthy
  db:
    env_file: 
      - path: ./.env 
        required: true
    image: "postgres:16.1-alpine3.19"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
